electro/cart/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove')
]

electro/electro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.urls.conf import include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('myauth/', include(('myauth.urls', 'myauth'), namespace='myauth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

electro/myauth/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('signin/', views.sign_in, name='signin'),
    path('user_page/<user_id>/', views.user_page, name='user_page'),
    path('admin_page/', views.my_admin_only_view, name='admin_page'),
    path('admin_change_order/<order_id>',
         views.change_order, name='admin_change_order')
]

electro/shop/urls.py
from collections import namedtuple
from django.urls import path
from shop import views


urlpatterns = [
    path('', views.home_page, name='home'),
    path('store/', views.store_page, name='store'),
    path('store/<category_slug>/',
         views.store_list_categories, name='categories_list'),
    path('product/<id>/<slug>/', views.product_page, name='product'),
    path('checkout/', views.checkout_page, name='checkout'),
    # path('order_create/', views.order_create, name='order_create')
]

electro/myauth/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.CharField(blank=True, max_length=32,)
    phone = models.CharField(blank=True, max_length=32)
    email = models.EmailField(blank=True, max_length=32)
    address = models.CharField(blank=True, max_length=32)
    country = models.CharField(blank=True, max_length=32)
    zipcode = models.CharField(blank=True, max_length=32)

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ('user',)

electro/myauth/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import fields
from shop.models import Product


class UserLoginForm(forms.Form):
    login = forms.CharField(required=False)
    password = forms.CharField(
        required=False, initial=False, widget=forms.PasswordInput)


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

electro/myauth/views.py
from django.contrib.auth.models import User, Group
from django.db.models.fields import EmailField
from django.shortcuts import get_object_or_404, redirect, render
from shop.models import Order, OrderItem
from .models import Profile
from .forms import UserLoginForm, AddProductForm
from django.contrib.auth import authenticate, login, logout
from django.conf import settings
from cart.cart import Cart
from shop.models import Product
from django.contrib.auth.decorators import user_passes_test


def log_in(request):
    if request.method == "POST":
        password = request.POST['password']
        username = request.POST['username']
        user = authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
            return redirect('shop:home')
        else:
            pass
    return render(request, 'myauth/login.html')


def log_out(request):
    logout(request)
    return redirect('myauth:login')


def sign_in(request):
    if request.method == "POST":
        password = request.POST['password']
        username = request.POST['username']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email']
        city = request.POST['city']
        phone = request.POST['phone']
        address = request.POST['address']
        country = request.POST['country']
        zipcode = request.POST['zipcode']
        user = User.objects.create(username=username, password=password,
                                   first_name=firstname, last_name=lastname, email=email, is_active=True)
        user.set_password(password)
        profile = Profile.objects.create(user=user)
        user.profile.city = city
        user.profile.phone = phone
        user.profile.email = email
        user.profile.address = address
        user.profile.country = country
        user.profile.zipcode = zipcode
        profile.save()
        group = Group.objects.get(name='customers')
        group.user_set.add(user)
        user.save()
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('shop:home')
        else:
            pass
    return render(request, 'myauth/signin.html')


def user_page(request, user_id):
    user_profile = get_object_or_404(Profile, user=user_id)
    user = get_object_or_404(User, username=user_profile)
    products_orders = Order.objects.filter(email=user.profile.email)
    list_with_order = []
    for i in products_orders:
        list_with_order.append(i)

    list_with_order_items = []
    for j in list_with_order:
        list_with_order_items.append(OrderItem.objects.filter(order_id=j))
    return render(request, 'myauth/user_page.html', {'user_profile': user_profile, 'user': user, 'orders': list_with_order_items, 'cart': cart(request)})


def cart(request):
    cart = request.session.get(settings.CART_SESSION_ID)
    count = 0
    subtotal = 0
    product_list = 0
    if cart:
        cart_values = cart.values()
        for item in cart_values:
            count += item['quantity']
            subtotal += item['quantity'] * float(item['price'])

        cart_items_id = cart.keys()
        product_list = Product.objects.filter(id__in=cart_items_id)
        cart = Cart(request)

    return {'count': count, 'product_list': product_list,  'subtotal': subtotal, 'cart': cart}


@user_passes_test(lambda u: u.is_staff)
def my_admin_only_view(request, *args, **kwargs):
    my_reverse_order_item = OrderItem.objects.all().order_by('-quantity')
    qery_with_name_quan = []

    for i in my_reverse_order_item:
        qery_with_name_quan.append([i.product, i.quantity])
    print(qery_with_name_quan)
    products_name_list = [qery_with_name_quan[i][0]
                          for i in range(len(qery_with_name_quan))]
    products_quantity_list = [qery_with_name_quan[i][1]
                              for i in range(len(qery_with_name_quan))]
    products = Product.objects.all()
    all_order = Order.objects.all()
    if request.method == 'POST':
        form = AddProductForm(request.POST)
        if form.is_valid():
            form.cleaned_data['category']
            form.cleaned_data['brand']
            form.cleaned_data['name']
            form.cleaned_data['slug']
            form.cleaned_data['main_photo']
            form.cleaned_data['photo_1']
            form.cleaned_data['photo_2']
            form.cleaned_data['photo_3']
            form.cleaned_data['description']
            form.cleaned_data['details']
            form.cleaned_data['price']
            form.cleaned_data['old_price']
            form.cleaned_data['stock']
            form.cleaned_data['available']
            form.cleaned_data['rait']

            form.save()
            return redirect('shop:store')
    else:
        form = AddProductForm()

    return render(request, 'myauth/admin_page.html', {'name': products_name_list,
                                                      'quantity': products_quantity_list,
                                                      'products': products,
                                                      'orders': all_order,
                                                      'form': form})


@user_passes_test(lambda u: u.is_staff)
def change_order(request, order_id):
    order = Order.objects.filter(id=order_id)
    for i in order:
        i.paid = 'True'
        i.save()
    return redirect('myauth:admin_page')

electro/myauth/templates/myauth/admin_page.html
{% extends '../base.html' %}
{% load static %}
{% block title %} Admin{% endblock %}
{% block content %}
<h2>Most sell product is:</h2>
<div class="container">
    <div class="col-md-8">
    <table class="user table">
        <thead>
            <tr>
                <th>Product</th>
                <th>Unit price</th>
                
            </tr>
        </thead>
        <tbody>
            {% for n in name %}
            <tr>
                
                <td><a href="{% url 'shop:product' n.id n.slug %}">{{n}}</a></td>
                
                <td>{{n.price}}</td>

            </tr>
           
            {% endfor %}
        </tbody>
    </table>
    </div>
    <div class="col-md-2">
    <table class="adm_quan table">
        <thead>
            <tr>
                <th>SOLD</th>
                
                
            </tr>
        </thead>
        <tbody>
            {% for q in quantity %}
            <tr>
                <td>{{q}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
</div>
<h2>All products</h2>
<table class="user table">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>In stock</th>
            <th>Brand</th>
            
            <th>Unit price</th>
            
        </tr>
    </thead>
    <tbody>
        {% for product in products %} 
        <tr>
            <td>
                <img width="50px" src="{% if product.main_photo %}{{ product.main_photo.url }}{% else %}{% static 'img/placeholder.png' %}{% endif %}" alt="{{ product.name }}">
            </td>
            <td>{{product}}</td>
            <td>{{product.stock}}</td>
            <td>{{product.brand}}</td>
            <td>{{product.price}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="container">
    <h1>Add new product</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" name="submit" id="">
    </form>
    <h1>Change order status</h1>
    {% for order in orders %}
        <a href="{% url 'myauth:admin_change_order' order_id=order.id %}">Order id : {{order.id}} User: {{order.first_name}}{{order.last_name}} Status: {{order.paid}}<br></a>
    {% endfor %}
</div>

{% endblock %}

electro/myauth/templates/myauth/login.html
{% extends '../base.html' %}
{% load static %}
{% block content %}
<h1>LOGIN</h1>

<form action="" method="post">
    {% csrf_token %}
    {{csrf_token}}
    <input type="text" name="username">
    <input type="password" name="password">
    <button type="submit">LOG IN</button>
</form>
		
{% endblock %}

electro/myauth/templates/myauth/signin.html
{% extends '../base.html' %}
{% load static %}
{% block content %}
<h1>Sign in</h1>

<form action="" method="post">
    {% csrf_token %}
    {{csrf_token}}
    <label for="username">username</label>
    <input type="text" name="username"><br>
    <label for="firstname">firstname</label>
    <input type="text" name="firstname"><br>
    <label for="lastname">lastname</label>
    <input type="text" name="lastname"><br>
    <label for="password">password</label>
    <input type="password" name="password"><br>
    <label for="email">email</label>
    <input type="email" name="email"><br>
    <label for="city">city</label>
    <input type="text" name="city"><br>
    <label for="phone">phone</label>
    <input type="text" name="phone"><br>
    <label for="address">address</label>
    <input type="text" name="address"><br>
    <label for="country">country</label>
    <input type="text" name="country"><br>
    <label for="zipcode">zipcode</label>
    <input type="text" name="zipcode"><br>
    <button type="submit">LOG IN</button>
</form>
		
{% endblock %}

electro/myauth/templates/myauth/user_page.html
{% extends '../base.html' %}
{% load static %}
{% block title %} Userpage{% endblock %}
{% block content %}
<div class="all_user_global">
<div class="container">
    <div id="main">
        <div class="row" id="real-estates-detail">
            <div class="col-lg-4 col-md-4 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <header class="panel-title">
                            <div class="text-center">
                                <strong>{{user.username}}</strong>
                            </div>
                        </header>
                    </div>
                <div class="panel-body">
                    <div class="text-center" id="author">
                        <img width="190px" height="190px" src="https://cdn.pixabay.com/photo/2018/04/18/18/56/user-3331257__340.png">
                            <h3>{{user.first_name}} {{user.last_name}}</h3>
                                <small class="label label-warning">{{user_profile.country}}</small>
                                <p class="sosmed-author">
                                <a href="#"><i class="fa fa-facebook" title="Facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter" title="Twitter"></i></a>
                                <a href="#"><i class="fa fa-google-plus" title="Google Plus"></i></a>
                                <a href="#"><i class="fa fa-linkedin" title="Linkedin"></i></a>
                                </p>
                    </div>
                </div>
            </div>
     </div>
     <div class="col-lg-8 col-md-8 col-xs-12">
        <div class="panel">
            <div class="panel-body">
                <div id="myTabContent" class="tab-content">
                <hr>
                    <div class="tab-pane fade active in" id="detail">
                    <h4>Info about user</h4>
                    <table class="table table-th-block">
                        <tbody>
                            <tr><td class="active">First name:</td><td>{{user.first_name}}</td></tr>
                            <tr><td class="active">Last name</td><td>{{user.last_name}}</td></tr>
                            <tr><td class="active">Country:</td><td>{{user_profile.country}}</td></tr>
                            <tr><td class="active">City:</td><td>{{user_profile.city}}</td></tr>
                            <tr><td class="active">Email:</td><td>{{user_profile.email}}</td></tr>
                            <tr><td class="active">Postcode</td><td>{{user_profile.zipcode}}</td></tr>
                            <tr><td class="active">Address</td><td>{{user_profile.address}}</td></tr>     
                        </tbody>
                    </table>
            </div>
            <div class="tab-pane fade" id="contact">
            <p></p>
            </div>
            </div>
        </div>
        </div>
        </div>
        </div>
    </div>
    <div id="order_user_item">
        <table class="user table">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Unit price</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                    {% for i in order %}
                <tr>
                    <td>
                        <img width="50px" src="{% if i.product.main_photo %}{{ i.product.main_photo.url }}{% else %}{% static 'img/placeholder.png' %}{% endif %}" alt="{{ i.product.name }}">
                    </td>
                    <td>{{i.product}}</td>
                    <td>{{i.quantity}}</td>
                    <td>{{i.price}}</td>
                </tr>
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
        <p>
            <a href="{% url 'shop:store' %}" class="btn light">Continue shopping</a>
        </p>
    </div>
</div>
{% endblock %}