electro/cart/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove')
]

electro/electro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.urls.conf import include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('myauth/', include(('myauth.urls', 'myauth'), namespace='myauth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

electro/myauth/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('signin/', views.sign_in, name='signin'),
    path('user_page/<user_id>/', views.user_page, name='user_page'),
    path('admin_page/', views.my_admin_only_view, name='admin_page'),
    path('admin_change_order/<order_id>',
         views.change_order, name='admin_change_order')
]

electro/shop/urls.py
from collections import namedtuple
from django.urls import path
from shop import views


urlpatterns = [
    path('', views.home_page, name='home'),
    path('store/', views.store_page, name='store'),
    path('store/<category_slug>/',
         views.store_list_categories, name='categories_list'),
    path('product/<id>/<slug>/', views.product_page, name='product'),
    path('checkout/', views.checkout_page, name='checkout'),
    # path('order_create/', views.order_create, name='order_create')
]

electro/shop/models.py
from django.db import models
from django.db.models.deletion import SET_NULL
from django.urls import reverse


class Category(models.Model):
    # db_index пошук в адмінці швидше працює
    name = models.CharField(max_length=200, db_index=True)
    # витягуєм абсолютну урлу гарний урл
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)  # упорядковуєм за полем
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:store', args=[self.slug])


class Brand(models.Model):
    # db_index пошук в адмінці швидше працює
    name = models.CharField(max_length=200, db_index=True)
    # витягуєм абсолютну урлу гарний урл
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_brand', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products', null=True, on_delete=models.SET_NULL)
    brand = models.ForeignKey(
        Brand, related_name='products', null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    main_photo = models.ImageField(upload_to='products/%Y/%m%d', blank=True)
    photo_1 = models.ImageField(upload_to='products/%Y/%m%d', blank=True)
    photo_2 = models.ImageField(upload_to='products/%Y/%m%d', blank=True)
    photo_3 = models.ImageField(upload_to='products/%Y/%m%d', blank=True)
    description = models.TextField()
    details = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    old_price = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    rait = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class Order(models.Model):
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    email = models.EmailField()
    address = models.CharField(max_length=250, null=True)
    postal_code = models.CharField(max_length=20, null=True)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    paid = models.BooleanField(default=False, null=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

electro/shop/forms.py
from django import forms
from django.db.models import fields
from .models import Category, Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email',
                  'address', 'postal_code', 'city']

electro/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.urls.conf import path
from .forms import OrderCreateForm
from shop.models import Product, Brand, Category, OrderItem
from cart.forms import CartAddProductForm
from django.conf import settings
from cart.cart import Cart

from django.core.paginator import Paginator
from django.shortcuts import render


def home_page(request):
    a = cart(request)
    print(a)
    return render(request, 'pages/index.html', {'cart':  cart(request)})


def store_page(request, category_slug=None, brand_slug=None):
    category = None
    brand = None
    categories = Category.objects.all().order_by('id')
    brands = Brand.objects.all()
    global_dict_filter = {
        'brands': brands,
        'categories': categories
    }
    category_id_list = []
    brand_id_list = []
    for c in range(len(global_dict_filter['categories'])):
        if request.POST.get(f"category-{c+1}", False) == 'on':
            category_id_list.append(c+1)
    for b in range(len(global_dict_filter['brands'])):
        if request.POST.get(f'brand-{b+1}', False) == 'on':
            brand_id_list.append(b+1)
    print('category', category_id_list)

    if category_id_list:
        products = Product.objects.filter(
            available=True, category__in=category_id_list)
        print(products[0].category.id)
    elif brand_id_list:
        products = Product.objects.filter(
            available=True, brand__in=brand_id_list)

    elif category_id_list and brand_id_list:
        products = Product.objects.filter(
            available=True, brand__in=brand_id_list, category__in=category_id_list)
    else:
        products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.objects.filter(category=category.slug)
    cart_product_form = CartAddProductForm()
    paginator = Paginator(products, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    product_count = len(products)
    return render(request, 'pages/store.html', {'category': category,
                                                'global_dict_filter': global_dict_filter,
                                                'products': products,
                                                'page_obj': page_obj,
                                                'cart_product_form': cart_product_form,
                                                # 'cart_items': pr,
                                                'cart': cart(request),
                                                'product_count': product_count})


def store_list_categories(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    brand = None
    Brands = Brand.objects.all()

    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)
    cart_product_form = CartAddProductForm()
    cart_items = request.session.get(settings.CART_SESSION_ID)
    product = cart_items.keys()
    paginator = Paginator(products, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'pages/store.html', {'category': category,
                                                'categories': categories,
                                                'page_obj': page_obj,
                                                'products': products,
                                                'cart_product_form': cart_product_form,
                                                'cart': cart(request)})


def product_page(request, id, slug):
    product = get_object_or_404(Product, slug=slug, id=id)
    cart_product_form = CartAddProductForm()
    category = get_object_or_404(Category, slug=product.category.slug)
    print(category)
    return render(request, 'pages/product.html', {'product_detail': product,
                                                  'cart_product_form': cart_product_form,
                                                  'cart':  cart(request),
                                                  'category': category})


def checkout_page(request):
    cart_1 = Cart(request)
    user = request.user
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart_1:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # очистка корзины
            cart_1.clear()
            return render(request, 'pages/order_have.html',
                          {'order': order})
    else:
        form = OrderCreateForm(initial={'first_name': user.first_name,
                                        'last_name': user.last_name,
                                        'email': user.profile.email,
                                        'address': user.profile.address,
                                        'postal_code': user.profile.zipcode,
                                        'city': user.profile.city})
    return render(request, 'pages/checkout.html',
                  {'cart': cart(request), 'form': form, 'user': user, 'cart_1': cart_1})


def cart(request):
    cart = request.session.get(settings.CART_SESSION_ID)
    count = 0
    subtotal = 0
    product_list = 0
    if cart:
        cart_values = cart.values()
        for item in cart_values:
            count += item['quantity']
            subtotal += item['quantity'] * float(item['price'])

        cart_items_id = cart.keys()
        product_list = Product.objects.filter(id__in=cart_items_id)
        cart = Cart(request)

    return {'count': count, 'product_list': product_list,  'subtotal': subtotal, 'cart': cart}

electro/templates/layouts/footer.html
{% load static %}
<!-- FOOTER -->
<footer id="footer">
    <!-- top footer -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h3 class="footer-title">About Us</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
                        <ul class="footer-links">
                            <li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
                            <li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
                            <li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h3 class="footer-title">Categories</h3>
                        <ul class="footer-links">
                            <li><a href="#">Hot deals</a></li>
                            <li><a href="#">Laptops</a></li>
                            <li><a href="#">Smartphones</a></li>
                            <li><a href="#">Cameras</a></li>
                            <li><a href="#">Accessories</a></li>
                        </ul>
                    </div>
                </div>

                <div class="clearfix visible-xs"></div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h3 class="footer-title">Information</h3>
                        <ul class="footer-links">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Orders and Returns</a></li>
                            <li><a href="#">Terms & Conditions</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h3 class="footer-title">Service</h3>
                        <ul class="footer-links">
                            <li><a href="#">My Account</a></li>
                            <li><a href="#">View Cart</a></li>
                            <li><a href="#">Wishlist</a></li>
                            <li><a href="#">Track My Order</a></li>
                            <li><a href="#">Help</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /top footer -->

    <!-- bottom footer -->
    <div id="bottom-footer" class="section">
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-12 text-center">
                    <ul class="footer-payments">
                        <li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
                        <li><a href="#"><i class="fa fa-credit-card"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
                    </ul>
                    <span class="copyright">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </span>
                </div>
            </div>
                <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /bottom footer -->
</footer>
<!-- /FOOTER -->

electro/templates/layouts/header.html
{% load static %}
<!-- HEADER -->
<header>
    <!-- TOP HEADER -->
    <div id="top-header">
        <div class="container">
            <ul class="header-links pull-left">
                <li><a href="tel:+ +021-95-51-84"><i class="fa fa-phone"></i> +021-95-51-84</a></li>
                <li><a href="mailto:email@email.com"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
                <li><a href="https://goo.gl/maps/gii9QK6MEU5c1DtB9"><i class="fa fa-map-marker"></i> 1734 Stonecoal Road</a></li>
            </ul>
            <ul class="header-links pull-right">
                <li><a href="#"><i class="fa fa-dollar"></i> USD</a></li>
                
                <li><a href="{% url 'myauth:admin_page' %}">{% if user.is_staff %}Admin page{% endif %}</a></li>
                <li><a href="{% url 'myauth:user_page' user_id=user.id %}">{% if user %}{{ user.get_username }}{% endif %}<i class="fa fa-user-o"></i> My Account</a></li>
                <li><a href="{% url 'myauth:login' %}"><i class="fa fa-user-o"></i> Log in</a></li>
                <li><a href="{% url 'myauth:signin' %}"><i class="fa fa-user-o"></i> Sign in</a></li>
                <li><a href="{% url 'myauth:logout' %}"><i class="fa fa-user-o"></i> Logout</a></li>
            </ul>
        </div>
    </div>
    <!-- /TOP HEADER -->

    <!-- MAIN HEADER -->
    <div id="header">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- LOGO -->
                <div class="col-md-3">
                    <div class="header-logo">
                        <a href="#" class="logo">
                            <img src="{% static './img/logo.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <!-- /LOGO -->

                <!-- SEARCH BAR -->
                <div class="col-md-6">
                    <div class="header-search">
                        <form>
                            <select class="input-select">
                                <option value="0">All Categories</option>
                                <option value="1">Category 01</option>
                                <option value="1">Category 02</option>
                            </select>
                            <input class="input" placeholder="Search here">
                            <button class="search-btn">Search</button>
                        </form>
                    </div>
                </div>
                <!-- /SEARCH BAR -->

                <!-- ACCOUNT -->
                <div class="col-md-3 clearfix">
                    <div class="header-ctn">
                        <!-- Wishlist -->
                        <div>
                            <a href="#">
                                <i class="fa fa-heart-o"></i>
                                <span>Your Wishlist</span>
                                <div class="qty">2</div>
                            </a>
                        </div>
                        <!-- /Wishlist -->

                        <!-- Cart -->
                        <div class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-shopping-cart"></i>
                                <span>Your Cart</span>
                                {% if count %}
                                <div class="qty">{{count}}</div>
                                {% endif %}
                                {% if cart.count %}
                                    <div class="qty">{{cart.count}}</div>
                                {% endif %}   
                            </a>
                            <div class="cart-dropdown">
                                <div class="cart-list">
                                {% for item in cart.cart %}
                                    <div class="product-widget">
                                        <div class="product-img">
                                            <img src="{% if item.product.main_photo %} {{ item.product.main_photo.url }} {% else %}{% static 'img/placeholder.jpg' %}{% endif %}"  alt="{{ product.name }}">
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-name"><a href="{% url 'shop:product' item.product.id item.product.slug %}">{{item.product.name}}</a></h3>
                                            <h4 class="product-price"><span class="qty">{{ item.quantity }}x</span>${{item.product.price}}</h4>
                                        </div>
                                        <button class="delete"><i class="fa fa-close"></i></button>
                                    </div>
                                {% endfor %}
                                    <h5>SUBTOTAL: {{cart.subtotal}}</h5>
                                </div>
                                
                                <div class="cart-btns">
                                    <a href="{% url 'cart:cart_detail' %}">View Cart</a>
                                    <a href="{% url 'shop:checkout'  %}">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
                                </div>
                            </div>
                        </div>
                        <!-- /Cart -->

                        <!-- Menu Toogle -->
                        <div class="menu-toggle">
                            <a href="#">
                                <i class="fa fa-bars"></i>
                                <span>Menu</span>
                            </a>
                        </div>
                        <!-- /Menu Toogle -->
                    </div>
                </div>
                <!-- /ACCOUNT -->
            </div>
            <!-- row -->
        </div>
        <!-- container -->
    </div>
    <!-- /MAIN HEADER -->
</header>
<!-- /HEADER -->

electro/templates/layouts/hot.html
{% load static %}
<!-- HOT DEAL SECTION -->
<div id="hot-deal" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <div class="hot-deal">
                    <ul class="hot-deal-countdown">
                        <li>
                            <div>
                                <h3>02</h3>
                                <span>Days</span>
                            </div>
                        </li>
                        <li>
                            <div>
                                <h3>10</h3>
                                <span>Hours</span>
                            </div>
                        </li>
                        <li>
                            <div>
                                <h3>34</h3>
                                <span>Mins</span>
                            </div>
                        </li>
                        <li>
                            <div>
                                <h3>60</h3>
                                <span>Secs</span>
                            </div>
                        </li>
                    </ul>
                    <h2 class="text-uppercase">hot deal this week</h2>
                    <p>New Collection Up to 50% OFF</p>
                    <a class="primary-btn cta-btn" href="#">Shop now</a>
                </div>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /HOT DEAL SECTION -->

electro/templates/layouts/navigation.html
{% load static %}
<!-- NAVIGATION -->
<nav id="navigation">
    <!-- container -->
    <div class="container">
        <!-- responsive-nav -->
        <div id="responsive-nav">
            <!-- NAV -->
            <ul class="main-nav nav navbar-nav">
                <li class="active"><a href="{% url 'shop:home' %}">Home</a></li>
                <li><a href="{% url 'shop:store' %}">Store</a></li>
                <li><a href="{% url 'shop:checkout' %}">Checkout</a></li>
            </ul>
            <!-- /NAV -->
        </div>
        <!-- /responsive-nav -->
    </div>
    <!-- /container -->
</nav>
<!-- /NAVIGATION -->

electro/templates/layouts/newslater.html
{% load static %}
<!-- NEWSLETTER -->
<div id="newsletter" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <div class="newsletter">
                    <p>Sign Up for the <strong>NEWSLETTER</strong></p>
                    <form>
                        <input class="input" type="email" placeholder="Enter Your Email">
                        <button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
                    </form>
                    <ul class="newsletter-follow">
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /NEWSLETTER -->

electro/templates/layouts/shop.html
{% load static %}	
<!-- SECTION -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- shop -->
                <div class="col-md-4 col-xs-6">
                    <div class="shop">
                        <div class="shop-img">
                            <img src="{% static './img/shop01.png' %}" alt="">
                        </div>
                        <div class="shop-body">
                            <h3>Laptop<br>Collection</h3>
                            <a href="#" class="cta-btn">Shop now <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                </div>
                <!-- /shop -->

                <!-- shop -->
                <div class="col-md-4 col-xs-6">
                    <div class="shop">
                        <div class="shop-img">
                            <img src="{% static './img/shop03.png' %}" alt="">
                        </div>
                        <div class="shop-body">
                            <h3>Accessories<br>Collection</h3>
                            <a href="#" class="cta-btn">Shop now <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                </div>
                <!-- /shop -->

                <!-- shop -->
                <div class="col-md-4 col-xs-6">
                    <div class="shop">
                        <div class="shop-img">
                            <img src="{% static './img/shop02.png' %}" alt="">
                        </div>
                        <div class="shop-body">
                            <h3>Cameras<br>Collection</h3>
                            <a href="#" class="cta-btn">Shop now <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                </div>
                <!-- /shop -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /SECTION -->