electro/cart/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove')
]

electro/electro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.urls.conf import include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('myauth/', include(('myauth.urls', 'myauth'), namespace='myauth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

electro/shop/urls.py
from collections import namedtuple
from django.urls import path
from shop import views


urlpatterns = [
    path('', views.home_page, name='home'),
    path('store/', views.store_page, name='store'),
    path('store/<category_slug>/',
         views.store_list_categories, name='categories_list'),
    path('product/<id>/<slug>/', views.product_page, name='product'),
    path('checkout/', views.checkout_page, name='checkout'),
    # path('order_create/', views.order_create, name='order_create')
]

electro/cart/models.py
from django.db import models

# Create your models here.

electro/cart/forms.py
from django import forms


# PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


# class CartAddProductForm(forms.Form):
#     quantity = forms.TypedChoiceField(
#         choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
#     update = forms.BooleanField(
#         required=False, initial=False, widget=forms.HiddenInput)


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

electro/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from shop.views import cart


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        print(form.cleaned_data)
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart_1 = Cart(request)

    return render(request, 'cart/detail.html', {'cart': cart(request), 'cart_1': cart_1, 'count': cart_1.__len__()})

electro/cart/templates/cart/detail.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Cart{% endblock %}
{% block content %}

    <div id="cart">
        <h1>CART {{ count }}</h1>  
        <table class="cart table">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit price</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for item in cart_1 %}
                    {% with product=item.product %}
                <tr>
                    <td>
                        <img width="50px" src="{% if product.main_photo %}{{ product.main_photo.url }}{% else %}{% static 'img/placeholder.png' %}{% endif %}" alt="{{ product.name }}">
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>
                        <a href="{% url 'cart:cart_remove' product_id=product.id %}">Remove</a>
                    </td>
                    <td>{{ product.price }}</td>

                    <td>{{ product.total_price }}</td>
                </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Total</th>
                    <th colspan="4"></th>
                    <th>${{ cart_1.get_total_price }}</th>
                    
                </tr>
            </tfoot>
        </table>
        <p>
            <a href="{% url 'shop:store' %}" class="btn light">Continue shopping</a>
            <a href="{% url 'shop:checkout' %}" class="btn">Checkout</a>
        </p>
    </div>
{% endblock %}