electro/cart/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove')
]

electro/electro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.urls.conf import include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('myauth/', include(('myauth.urls', 'myauth'), namespace='myauth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

electro/shop/urls.py
from collections import namedtuple
from django.urls import path
from shop import views


urlpatterns = [
    path('', views.home_page, name='home'),
    path('store/', views.store_page, name='store'),
    path('store/<category_slug>/',
         views.store_list_categories, name='categories_list'),
    path('product/<id>/<slug>/', views.product_page, name='product'),
    path('checkout/', views.checkout_page, name='checkout'),
    # path('order_create/', views.order_create, name='order_create')
]

electro/templates/pages/checkout.html
{% extends '../base.html' %}
{% load static %}
{% block title %} Checkout{% endblock %}
{% block content %}
	
{% include '../layouts-checkout/breadcrumb.html' %}	
<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">

            <div class="col-md-7">
                {% include '../layouts-checkout/biling_details.html' %}
                {% include '../layouts-checkout/shiping_details.html' %}
                {% include '../layouts-checkout/order_notes.html' %}
            </div>

            {% include '../layouts-checkout/order_details.html' %}
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /SECTION -->

		
		

		

		
{% endblock %}

electro/templates/pages/index.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
	
	
		

		{% include '../layouts/shop.html' %}
		{% include '../layouts/newproduct.html' %}
		{% include '../layouts/hot.html' %}
		{% include '../layouts/top.html' %}
		{% include '../layouts/widgets.html' %}

		
		

		

		
{% endblock %}

electro/templates/pages/order_have.html
{% extends '../base.html' %}
{% load static %}
{% block title %} Checkout{% endblock %}
{% block content %}
    <h1>Thank you, your order submited!!!</h1>
{% endblock %}

electro/templates/pages/product.html
{% extends '../base.html' %}
{% load static %}
{% block title %} product{% endblock %}
{% block content %}
{% include '../layouts-store/breadcrumbs.html' %}
		
	<!-- SECTION -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                {% include '../layouts-product/main-img.html' %}

                {% include '../layouts-product/thumb-img.html' %}

                {% include '../layouts-product/product-details.html' %}

                {% include '../layouts-product/product-tab.html' %}
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /SECTION -->
    {% include '../layouts-product/related.html' %}
		

		
		

		

		
{% endblock %}

electro/templates/pages/store.html
{% extends '../base.html' %}
{% load static %}
{% block title %} Store{% endblock %}
{% block cart %} {{ cart_product_form.quantity }}{% endblock %}
{% block content %}
{% include '../layouts-store/breadcrumbs.html' %}
    
	<!-- SECTION -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- ASIDE -->
                <div id="aside" class="col-md-3">
                    <!-- aside Widget -->
                    <div class="aside">
                        <h3 class="aside-title">Categories</h3>
                        <div class="checkbox-filter">
                            <form action="" method="post">
                            {% csrf_token %}
                            {% for category_item in global_dict_filter.categories %}
                           
                            <div class="input-checkbox">
                                <input type="checkbox" id="category-{{forloop.counter}}" name="category-{{forloop.counter}}">
                                <label for="category-{{forloop.counter}}">
                                    <span></span>
                                    {{category_item}}
                                    
                                </label>
                            </div>
                            
                            {% endfor %}
                            <br>
                            <h3 class="aside-title">Brand</h3>
                            {% for brand_item in global_dict_filter.brands %}
                            <div class="input-checkbox">
                                <input type="checkbox" id="brand-{{forloop.counter}}" name="brand-{{forloop.counter}}">
                                <label for="brand-{{forloop.counter}}">
                                    <span></span>
                                    {{brand_item}}
                                    
                                </label>
                            </div>
                            {% endfor %}
                            <button type="submit">Find</button>
                        </form>
                        </div>
                    </div>
                    <!-- /aside Widget -->

                    <!-- aside Widget -->
                    <div class="aside">
                        <h3 class="aside-title">Price</h3>
                        <div class="price-filter">
                            <div id="price-slider"></div>
                            <div class="input-number price-min">
                                <input id="price-min" type="number">
                                <span class="qty-up">+</span>
                                <span class="qty-down">-</span>
                            </div>
                            <span>-</span>
                            <div class="input-number price-max">
                                <input id="price-max" type="number">
                                <span class="qty-up">+</span>
                                <span class="qty-down">-</span>
                            </div>
                        </div>
                    </div>
                    <!-- /aside Widget -->

                    <!-- aside Widget -->
                    <!-- <div class="aside">
                        <h3 class="aside-title">Brand</h3>
                        <div class="checkbox-filter">
                            <form action="" method="post">
                                {% for brand_item in brands %}
                                {% csrf_token %}
                                <div class="input-checkbox">
                                    <input type="checkbox" id="brand-{{forloop.counter}}" name="brand-{{forloop.counter}}">
                                    <label for="category-{{forloop.counter}}">
                                        <span></span>
                                        {{brand_item}}
                                    </label>
                                </div>
                                
                                {% endfor %}
                                <button type="submit">Find</button>
                            </form>
                        </div>
                    </div> -->
                    <!-- /aside Widget -->

                    <!-- aside Widget -->
                    <div class="aside">
                        <h3 class="aside-title">Top selling</h3>
                        <div class="product-widget">
                            <div class="product-img">
                                <img src=" {% static './img/product01.png' %}"  alt="">
                            </div>
                            <div class="product-body">
                                <p class="product-category">Category</p>
                                <h3 class="product-name"><a href="#">product name goes here</a></h3>
                                <h4 class="product-price">$980.00 <del class="product-old-price">$990.00</del></h4>
                            </div>
                        </div>

                        <div class="product-widget">
                            <div class="product-img">
                                <img src=" {% static './img/product02.png' %}"  alt="">
                            </div>
                            <div class="product-body">
                                <p class="product-category">Category</p>
                                <h3 class="product-name"><a href="#">product name goes here</a></h3>
                                <h4 class="product-price">$980.00 <del class="product-old-price">$990.00</del></h4>
                            </div>
                        </div>

                        <div class="product-widget">
                            <div class="product-img">
                                <img src=" {% static './img/product03.png' %}"  alt="">
                            </div>
                            <div class="product-body">
                                <p class="product-category">Category</p>
                                <h3 class="product-name"><a href="#">product name goes here</a></h3>
                                <h4 class="product-price">$980.00 <del class="product-old-price">$990.00</del></h4>
                            </div>
                        </div>
                    </div>
                    <!-- /aside Widget -->
                </div>
                <!-- /ASIDE -->

                <!-- STORE -->
                <div id="store" class="col-md-9">
                    <!-- store top filter -->
                    <div class="store-filter clearfix">
                        <div class="store-sort">
                            <label>
                                Sort By:
                                <select class="input-select">
                                    <option value="0">Popular</option>
                                    <option value="1">Position</option>
                                </select>
                            </label>

                            <label>
                                Show:
                                <select class="input-select">
                                    <option value="0">20</option>
                                    <option value="1">50</option>
                                </select>
                            </label>
                        </div>
                        <ul class="store-grid">
                            <li class="active"><i class="fa fa-th"></i></li>
                            <li><a href="#"><i class="fa fa-th-list"></i></a></li>
                        </ul>
                    </div>
                    <!-- /store top filter -->

                    <!-- store products -->
                    <div class="row">
                        {% for product in page_obj %}
                        <!-- product -->
                        <div class="col-md-4 col-xs-6">
                            <div class="product">
                                <div class="product-img">
                                    <img src="{% if product.main_photo %} {{ product.main_photo.url }} {% else %}{% static 'img/placeholder.jpg' %}{% endif %}"  alt="{{ product.name }}" style="height: 230px;">
                                    <div class="product-label">
                                        <span class="sale">-30%</span>
                                        <span class="new">NEW</span>
                                    </div>
                                </div>
                                <div class="product-body">
                                    <p class="product-category"><a href="{% url 'shop:categories_list' category_slug=product.category.slug  %}">{{ product.category }}</a></p>
                                    <h3 class="product-name"><a href="{% url 'shop:product' product.id product.slug %}">{{ product.name }}</a></h3>
                                    <h4 class="product-price">{{ product.price }}{% if product.old_price %} <del class="product-old-price">{{ product.old_price }}</del>{% endif %}</h4>
                                    <div class="product-rating">
                                        {% for i in "12345" %}
                                            {% if product.rait > forloop.counter0 %}<i class="fa fa-star"></i>{% else %}<i class="fa fa-star-o"></i>{% endif %}
                                        {% endfor %}
                                    </div>
                                    
                                    <div class="product-btns">
                                        <button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
                                        <button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">add to compare</span></button>
                                        <button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>
                                    </div>
                                </div>
                                
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {{ cart_product_form }}
                                    {% csrf_token %}
                                    <input class="add-to-cart-btn btn" type="submit" value="Add to cart" >
                                </form>
                                <!-- <div class="add-to-cart">
                                    <form action="{% url 'cart:cart_add' product_id=product.id %}" method="POST">{{ CartAddProductForm }}
                                        <a href="{% url 'cart:cart_add' product_id=product.id %}" class="add-to-cart-btn btn"><i class="fa fa-shopping-cart"></i> add to cart</a>
                                    </form>
                                    
                                </div> -->
                            </div>
                        </div>
                        {% endfor %}
                    
                        <div class="clearfix visible-sm visible-xs"></div>
                    </div>
                        <div class="store-filter clearfix">
                            <span class="store-qty">Showing 20-100 products</span>   
                        
                            <div class="pagination">
                                <ul class="step-links store-pagination">
                                    {% if page_obj.has_previous %}
                                    <li><a href="?page=1">&laquo;</a></li>
                                    <li><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i></a></li>
                                    {% endif %}
                                    {% for i in page_obj.paginator %}
                                        {% if forloop.counter == page_obj.number %}
                                        <li class="active current">
                                            {{ page_obj.number }}
                                        </li>
                                        {% else %}
                                        <li><a href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
                                        {% endif %}
                                    {% endfor %}                        
                                    {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right"></i></a></li>
                                    <li><a href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                                     
                     
                    
                    </div>
                    <!-- /store products -->
                    
                    <!-- store bottom filter -->
                    
                    <!-- /store bottom filter -->
                </div>
                <!-- /STORE -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /SECTION -->	
	
		


		
		

		

		
{% endblock %}